name = "FlagSets"
uuid = "c7ad171a-416d-44a6-be7b-07ee749f090e"
authors = ["Jéssica Milaré <jessymilare@gmail.com>"]
version = "0.2.1"

[deps]

[compat]
julia = "1"

[extras]
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Serialization", "Test"]
